/** @format */

import { StyleSheet, Dimensions } from 'react-native';
import { Color, Fonts } from '@common';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: Color.border,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
  },
  editButton: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: '#ff8a65',
    borderRadius: 20,
  },
  editButtonText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: Fonts.regular,
    fontWeight: '500',
  },
  section: {
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: Color.border,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: Fonts.bold,
    fontWeight: '600',
    marginBottom: 12,
  },
  orderItem: {
    flexDirection: 'row',
    marginBottom: 12,
    paddingVertical: 12,
    paddingHorizontal: 15,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    alignItems: 'flex-start',
    minHeight: 100,
  },
  productImageContainer: {
    width: 80,
    height: 80,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  productImage: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
    backgroundColor: '#f5f5f5',
    resizeMode: 'cover',
  },
  productDetails: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingLeft: 0,
  },
  productInfoBottomRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginTop: 8,
    marginLeft: 0,
    paddingLeft: 0,
  },
  productInfoLeft: {
    marginTop: 8,
    marginLeft: 0,
    paddingLeft: 0,
  },
  productInfoRight: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    flex: 0,
  },
  productName: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    fontWeight: '500',
    marginBottom: 8,
    lineHeight: 18,
    flex: 1,
  },
  productVariant: {
    fontSize: 12,
    fontFamily: Fonts.regular,
    color: Color.grey,
    marginBottom: 6,
    marginLeft: 0,
    paddingLeft: 0,
  },
  productPrice: {
    fontSize: 13,
    fontFamily: Fonts.regular,
    fontWeight: '500',
    color: Color.text,
    marginLeft: 0,
    paddingLeft: 0,
    paddingBottom: 0,
  },
  quantityAndTotalContainer: {
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    minHeight: 60,
    display: 'none',
  },
  quantitySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    minWidth: 80,
    justifyContent: 'space-between',
    display: 'none'
  },
  quantityButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityButtonText: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    color: '#333',
    fontWeight: '500',
  },
  quantityText: {
    fontSize: 14,
    fontFamily: Fonts.medium,
    fontWeight: '500',
    color: '#333',
    textAlign: 'center',
    minWidth: 20,
  },
  itemTotal: {
    fontSize: 1,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
    color: Color.text,
    marginLeft: 10,
    opacity: 0,
    
  },
  totalAndQuantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
  },
  addressContainer: {
    backgroundColor: '#f8f9fa',
    padding: 15,
    borderRadius: 8,
    marginTop: 8,
  },
  addressText: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    marginBottom: 3,
  },
  // Coupon Styles
  couponInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  couponInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    fontFamily: Fonts.regular,
    marginRight: 10,
  },
  applyCouponButton: {
    backgroundColor: Color.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  applyCouponText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: Fonts.regular,
    fontWeight: '500',
  },
  appliedCouponContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#e8f5e8',
    padding: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  appliedCouponInfo: {
    flex: 1,
  },
  appliedCouponCode: {
    fontSize: 14,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  appliedCouponDiscount: {
    fontSize: 12,
    fontFamily: Fonts.regular,
  },
  removeCouponButton: {
    backgroundColor: '#ff6b6b',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  removeCouponText: {
    color: '#fff',
    fontSize: 12,
    fontFamily: Fonts.regular,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  priceLabel: {
    fontSize: 14,
    fontFamily: Fonts.regular,
  },
  priceValue: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    fontWeight: '500',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: Color.border,
    marginTop: 10,
    paddingTop: 15,
  },
  totalLabel: {
    fontSize: 18,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
  },
  totalValue: {
    fontSize: 18,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
    color: Color.primary,
  },
  buttonContainer: {
    paddingHorizontal: 20,
    paddingTop: 0,
    paddingBottom: 8,
    backgroundColor: 'transparent',
  },
  proceedButton: {
    backgroundColor: '#ff8a65',
    borderRadius: 8,
    paddingVertical: 10,
  },
  proceedButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
  },
  // Coupon Card Styles
  sectionSubtitle: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    fontWeight: '500',
    marginTop: 15,
    marginBottom: 15,
  },
  couponListView: {
    marginTop: 10,
  },
  couponGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginHorizontal: -5,
  },
  couponCard: {
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#e0e0e0',
    borderRadius: 12,
    padding: 15,
    marginHorizontal: 5,
    marginVertical: 5,
    width: '48%',
    minHeight: 90,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  couponCardSelected: {
    backgroundColor: Color.primary,
    borderColor: Color.primary,
  },
  couponCardCode: {
    fontSize: 16,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
    color: Color.primary,
    marginBottom: 6,
    textAlign: 'center',
  },
  couponCardCodeSelected: {
    color: '#ffffff',
  },
  couponCardDesc: {
    fontSize: 12,
    fontFamily: Fonts.regular,
    color: Color.grey,
    marginBottom: 8,
    lineHeight: 16,
    textAlign: 'center',
  },
  couponCardDescSelected: {
    color: '#ffffff',
  },
  couponCardAmount: {
    fontSize: 14,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
    color: '#2ecc71',
    textAlign: 'center',
  },
  couponCardAmountSelected: {
    color: '#ffffff',
  },
  noCouponsText: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 20,
    color: Color.grey,
  },
  loadingText: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 20,
    color: Color.grey,
  },
});
